import images from '~/assest/images';
export const collection7day = [
    {
        avatar: images.top1,
        index: '1',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top2,
        index: '2',
        name: 'NFT Worlds',
        floor: '0.85ETH',
        eth: '6.8k ETH',
        price: '$9.4M',
        percent: '+300.7%',
    },
    {
        avatar: images.top3,
        index: '3',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top4,
        index: '4',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top5,
        index: '5',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top6,
        index: '6',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top2,
        index: '7',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top4,
        index: '8',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top5,
        index: '9',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top6,
        index: '10',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top3,
        index: '11',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top1,
        index: '12',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
];
export const collection30day = [
    {
        avatar: images.top6,
        index: '1',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top4,
        index: '2',
        name: 'NFT Worlds',
        floor: '0.85ETH',
        eth: '6.8k ETH',
        price: '$9.4M',
        percent: '+300.7%',
    },
    {
        avatar: images.top1,
        index: '3',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top3,
        index: '4',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top2,
        index: '5',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top5,
        index: '6',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top2,
        index: '7',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top5,
        index: '8',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top3,
        index: '9',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top1,
        index: '10',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top4,
        index: '11',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
    {
        avatar: images.top6,
        index: '12',
        name: 'NFT Worlds',
        floor: '0.80ETH',
        eth: '5.8k ETH',
        price: '$8.4M',
        percent: '+294.7%',
    },
];

export const tranding = [
    {
        avatar: images.tranding1,
        name: 'Rare Crypto',
        top: '#QA5200 The Kive',
        price: '0.03 ETH',
        bid: '0.07 ETH',
    },
    {
        avatar: images.tranding2,
        name: 'Kive Boy',
        top: '#QA5200 The Kive',
        price: '0.03 ETH',
        bid: '0.07 ETH',
    },
    {
        avatar: images.tranding3,
        name: 'Kive Boy',
        top: '#QA5200 The Kive',
        price: '0.03 ETH',
        bid: '0.07 ETH',
    },
    {
        avatar: images.tranding4,
        name: 'Kive Boy',
        top: '#QA5200 The Kive',
        price: '0.03 ETH',
        bid: '0.07 ETH',
    },
];
