const images = {
    logo: require('~/assest/images/logo.svg').default,
    heroimg: require('~/assest/images/Heroimg.svg').default,
    creators: require('~/assest/images/Creators.svg').default,
    gamehome: require('~/assest/images/GameHome.svg').default,
    arthome: require('~/assest/images/ArtHome.svg').default,
    metarverhome: require('~/assest/images/MetarverHome.svg').default,
    musichome: require('~/assest/images/MusicHome.svg').default,
    sporthome: require('~/assest/images/SportHome.svg').default,
    photographyhome: require('~/assest/images/PhotographyHome.svg').default,
    playicon: require('~/assest/images/Playicon.svg').default,
    arrowhome: require('~/assest/images/ArrowHome.svg').default,
    bgheroimg: require('~/assest/images/bgHeroimg.svg').default,
    top1: require('~/assest/images/Top1.svg').default,
    top2: require('~/assest/images/Top2.svg').default,
    top3: require('~/assest/images/Top3.svg').default,
    top4: require('~/assest/images/Top4.svg').default,
    top5: require('~/assest/images/Top5.svg').default,
    top6: require('~/assest/images/Top6.svg').default,
    tranding1: require('~/assest/images/tranding1.svg').default,
    tranding2: require('~/assest/images/tranding2.svg').default,
    tranding3: require('~/assest/images/tranding3.svg').default,
    tranding4: require('~/assest/images/tranding4.svg').default,
    insight: require('~/assest/images/Insight.svg').default,
    insight1: require('~/assest/images/Insight1.svg').default,
    insight2: require('~/assest/images/Insight2.svg').default,
    iconfooter: require('~/assest/images/IconFooter.svg').default,
};

export default images;
